[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 921600

; 💡 これを追記！自動で照度センサーのライブラリがダウンロードされます
lib_deps =
    claws/BH1750 @ ^1.3.0
    bblanchon/ArduinoJson @ ^7.0.4
    # ★ BMP280用のライブラリを追加します
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.14